version: "3"
services:
  web:
    build: pwa/.
    ports:
      - "8001:8080"
    environment:
      TLS_KEY: /certs/docker.data.techcollege.dk.key
      TLS_CRT: /certs/docker.data.techcollege.dk.crt
    depends_on:
      - api
  api:
    build: api/.
    ports:
      - "8000:5000"
      - "8002:5001"
    environment:
      ASPNETCORE_URLS: "https://+:443"
      ASPNETCORE_Kestrel__Certificates__Default__Path: "/app/certificate/wiseguy.pfx"
      ASPNETCORE_Kestrel__Certificates__Default__Password: "signal4-youToo"
    depends_on:
      - db
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "Cloud9-district"
      ACCEPT_EULA: "Y"

