version: "3.4"
services:
  web:
    build: pwa-production/.
    volumes:
      - /etc/docker/certs:/pwacerts
        
    ports:
      - "8000:8080"
    environment:
      TLS_KEY: /pwacerts/docker.data.techcollege.dk.key
      TLS_CRT: /pwacerts/docker.data.techcollege.dk.crt
    depends_on:
      - api
  api:
    build: api/.
    ports:
      - "8001:5000"
      - "8002:5001"
    volumes:
      - /etc/docker/certs:/apicerts
    environment:
      ASPNETCORE_URLS: "https://+:443"
      ASPNETCORE_Kestrel__Certificates__Default__Path: "/apicerts/docker.data.techcollege.dk.pfx"
      ASPNETCORE_Kestrel__Certificates__Default__Password: "signal4-youToo"
    depends_on:
      - db
  db:
    build: db/.
    environment:
      SA_PASSWORD: "Cloud9-district"
      ACCEPT_EULA: "Y"

